"""compliance control graph

Revision ID: 8be45f9c97b9
Revises: e2afb574f3bb
Create Date: 2026-08-19 12:28:52.508866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8be45f9c97b9'
down_revision: Union[str, None] = 'e2afb574f3bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('controls',
    sa.Column('control_code', sa.String(length=50), nullable=False),
    sa.Column('domain', sa.String(length=120), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_controls_control_code'), 'controls', ['control_code'], unique=True)
    op.create_index(op.f('ix_controls_domain'), 'controls', ['domain'], unique=False)
    op.create_table('regulations',
    sa.Column('regulation_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('short_name', sa.String(length=100), nullable=True),
    sa.Column('regulator', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regulations_regulation_code'), 'regulations', ['regulation_code'], unique=True)
    op.create_table('regulatory_sources',
    sa.Column('source_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('publisher', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('document_type', sa.String(length=100), nullable=True),
    sa.Column('retrieved_on', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regulatory_sources_source_code'), 'regulatory_sources', ['source_code'], unique=True)
    op.create_table('control_tests',
    sa.Column('test_code', sa.String(length=50), nullable=False),
    sa.Column('control_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_control_tests_control_id'), 'control_tests', ['control_id'], unique=False)
    op.create_index(op.f('ix_control_tests_test_code'), 'control_tests', ['test_code'], unique=True)
    op.create_table('control_versions',
    sa.Column('control_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('owner_type', sa.Enum('COMPLIANCE_MANAGER', 'OPERATIONS_MANAGER', 'FLEET_MANAGER', 'SITE_MANAGER', 'SCHEDULER', 'EXECUTIVE', 'SUPPLIER_MANAGER', name='control_owner_type', native_enum=False), nullable=False),
    sa.Column('frequency', sa.Enum('CONTINUOUS', 'PER_TRIP', 'PER_SHIFT', 'DAILY', 'WEEKLY', 'MONTHLY', 'QUARTERLY', 'ANNUAL', 'EVENT_DRIVEN', name='control_frequency', native_enum=False), nullable=False),
    sa.Column('automation_level', sa.Enum('MANUAL', 'SEMI_AUTOMATED', 'AUTOMATED', name='automation_level', native_enum=False), nullable=False),
    sa.Column('psoe_relevance', postgresql.ARRAY(sa.String(length=20)), nullable=False),
    sa.Column('procedure_reference', sa.String(length=500), nullable=True),
    sa.Column('change_note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'IN_REVIEW', 'APPROVED', 'ACTIVE', 'SUPERSEDED', 'RETIRED', name='lifecycle_status', native_enum=False), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('source_reference', sa.String(length=500), nullable=True),
    sa.Column('reviewed_by_id', sa.UUID(), nullable=True),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('control_id', 'version', name='uq_control_version')
    )
    op.create_index(op.f('ix_control_versions_control_id'), 'control_versions', ['control_id'], unique=False)
    op.create_index(op.f('ix_control_versions_effective_from'), 'control_versions', ['effective_from'], unique=False)
    op.create_index(op.f('ix_control_versions_effective_to'), 'control_versions', ['effective_to'], unique=False)
    op.create_index(op.f('ix_control_versions_status'), 'control_versions', ['status'], unique=False)
    op.create_table('obligations',
    sa.Column('obligation_code', sa.String(length=50), nullable=False),
    sa.Column('regulation_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('cor_role_codes', postgresql.ARRAY(sa.String(length=50)), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'IN_REVIEW', 'APPROVED', 'ACTIVE', 'SUPERSEDED', 'RETIRED', name='lifecycle_status', native_enum=False), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('source_reference', sa.String(length=500), nullable=True),
    sa.Column('reviewed_by_id', sa.UUID(), nullable=True),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['regulation_id'], ['regulations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('obligation_code', 'version', name='uq_obligation_code_version')
    )
    op.create_index(op.f('ix_obligations_effective_from'), 'obligations', ['effective_from'], unique=False)
    op.create_index(op.f('ix_obligations_effective_to'), 'obligations', ['effective_to'], unique=False)
    op.create_index(op.f('ix_obligations_obligation_code'), 'obligations', ['obligation_code'], unique=False)
    op.create_index(op.f('ix_obligations_regulation_id'), 'obligations', ['regulation_id'], unique=False)
    op.create_index(op.f('ix_obligations_status'), 'obligations', ['status'], unique=False)
    op.create_table('regulation_versions',
    sa.Column('regulation_id', sa.UUID(), nullable=False),
    sa.Column('regulatory_source_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('jurisdiction_codes', postgresql.ARRAY(sa.String(length=10)), nullable=False),
    sa.Column('requires_control_review', sa.Boolean(), nullable=False),
    sa.Column('change_note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'IN_REVIEW', 'APPROVED', 'ACTIVE', 'SUPERSEDED', 'RETIRED', name='lifecycle_status', native_enum=False), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('source_reference', sa.String(length=500), nullable=True),
    sa.Column('reviewed_by_id', sa.UUID(), nullable=True),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['regulation_id'], ['regulations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['regulatory_source_id'], ['regulatory_sources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('regulation_id', 'version', name='uq_regulation_version')
    )
    op.create_index(op.f('ix_regulation_versions_effective_from'), 'regulation_versions', ['effective_from'], unique=False)
    op.create_index(op.f('ix_regulation_versions_effective_to'), 'regulation_versions', ['effective_to'], unique=False)
    op.create_index(op.f('ix_regulation_versions_regulation_id'), 'regulation_versions', ['regulation_id'], unique=False)
    op.create_index(op.f('ix_regulation_versions_status'), 'regulation_versions', ['status'], unique=False)
    op.create_table('applicability_rules',
    sa.Column('rule_code', sa.String(length=50), nullable=False),
    sa.Column('obligation_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'IN_REVIEW', 'APPROVED', 'ACTIVE', 'SUPERSEDED', 'RETIRED', name='lifecycle_status', native_enum=False), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('source_reference', sa.String(length=500), nullable=True),
    sa.Column('reviewed_by_id', sa.UUID(), nullable=True),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['obligation_id'], ['obligations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_code', 'version', name='uq_applicability_rule_version')
    )
    op.create_index(op.f('ix_applicability_rules_effective_from'), 'applicability_rules', ['effective_from'], unique=False)
    op.create_index(op.f('ix_applicability_rules_effective_to'), 'applicability_rules', ['effective_to'], unique=False)
    op.create_index(op.f('ix_applicability_rules_obligation_id'), 'applicability_rules', ['obligation_id'], unique=False)
    op.create_index(op.f('ix_applicability_rules_rule_code'), 'applicability_rules', ['rule_code'], unique=False)
    op.create_index(op.f('ix_applicability_rules_status'), 'applicability_rules', ['status'], unique=False)
    op.create_table('control_test_versions',
    sa.Column('control_test_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('test_logic_description', sa.Text(), nullable=False),
    sa.Column('test_type', sa.Enum('DETERMINISTIC', 'ANALYTICAL', 'AI_ASSISTED', 'MANUAL', name='control_test_type', native_enum=False), nullable=False),
    sa.Column('rule_configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('severity_configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('human_review_required', sa.Boolean(), nullable=False),
    sa.Column('psoe_impact', postgresql.ARRAY(sa.String(length=20)), nullable=False),
    sa.Column('change_note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'IN_REVIEW', 'APPROVED', 'ACTIVE', 'SUPERSEDED', 'RETIRED', name='lifecycle_status', native_enum=False), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('source_reference', sa.String(length=500), nullable=True),
    sa.Column('reviewed_by_id', sa.UUID(), nullable=True),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['control_test_id'], ['control_tests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('control_test_id', 'version', name='uq_control_test_version')
    )
    op.create_index(op.f('ix_control_test_versions_control_test_id'), 'control_test_versions', ['control_test_id'], unique=False)
    op.create_index(op.f('ix_control_test_versions_effective_from'), 'control_test_versions', ['effective_from'], unique=False)
    op.create_index(op.f('ix_control_test_versions_effective_to'), 'control_test_versions', ['effective_to'], unique=False)
    op.create_index(op.f('ix_control_test_versions_status'), 'control_test_versions', ['status'], unique=False)
    op.create_index(op.f('ix_control_test_versions_test_type'), 'control_test_versions', ['test_type'], unique=False)
    op.create_table('risks',
    sa.Column('risk_code', sa.String(length=50), nullable=False),
    sa.Column('obligation_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('inherent_likelihood', sa.Enum('RARE', 'UNLIKELY', 'POSSIBLE', 'LIKELY', 'ALMOST_CERTAIN', name='risk_likelihood', native_enum=False), nullable=True),
    sa.Column('inherent_consequence', sa.Enum('INSIGNIFICANT', 'MINOR', 'MODERATE', 'MAJOR', 'SEVERE', name='risk_consequence', native_enum=False), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'IN_REVIEW', 'APPROVED', 'ACTIVE', 'SUPERSEDED', 'RETIRED', name='lifecycle_status', native_enum=False), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('source_reference', sa.String(length=500), nullable=True),
    sa.Column('reviewed_by_id', sa.UUID(), nullable=True),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['obligation_id'], ['obligations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('risk_code', 'version', name='uq_risk_code_version')
    )
    op.create_index(op.f('ix_risks_effective_from'), 'risks', ['effective_from'], unique=False)
    op.create_index(op.f('ix_risks_effective_to'), 'risks', ['effective_to'], unique=False)
    op.create_index(op.f('ix_risks_obligation_id'), 'risks', ['obligation_id'], unique=False)
    op.create_index(op.f('ix_risks_risk_code'), 'risks', ['risk_code'], unique=False)
    op.create_index(op.f('ix_risks_status'), 'risks', ['status'], unique=False)
    op.create_table('control_risk_links',
    sa.Column('control_id', sa.UUID(), nullable=False),
    sa.Column('risk_id', sa.UUID(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['risk_id'], ['risks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('control_id', 'risk_id', name='uq_control_risk_link')
    )
    op.create_index(op.f('ix_control_risk_links_control_id'), 'control_risk_links', ['control_id'], unique=False)
    op.create_index(op.f('ix_control_risk_links_risk_id'), 'control_risk_links', ['risk_id'], unique=False)
    op.create_table('evidence_requirements',
    sa.Column('requirement_code', sa.String(length=50), nullable=False),
    sa.Column('control_test_version_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_type', sa.Enum('TMS', 'EWD', 'TELEMATICS', 'FLEET_MAINTENANCE', 'HR_LMS', 'WMS', 'WEIGHBRIDGE', 'PERMIT_REGISTER', 'DRIVER_APP', 'INCIDENT_SYSTEM', 'SUPPLIER_PORTAL', 'DOCUMENT', 'MANUAL_ATTESTATION', name='evidence_source_type', native_enum=False), nullable=False),
    sa.Column('required_fields', postgresql.ARRAY(sa.String(length=100)), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('max_age_days', sa.Integer(), nullable=True),
    sa.Column('retention_note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'IN_REVIEW', 'APPROVED', 'ACTIVE', 'SUPERSEDED', 'RETIRED', name='lifecycle_status', native_enum=False), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('source_reference', sa.String(length=500), nullable=True),
    sa.Column('reviewed_by_id', sa.UUID(), nullable=True),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['control_test_version_id'], ['control_test_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requirement_code', 'version', name='uq_evidence_requirement_version')
    )
    op.create_index(op.f('ix_evidence_requirements_control_test_version_id'), 'evidence_requirements', ['control_test_version_id'], unique=False)
    op.create_index(op.f('ix_evidence_requirements_effective_from'), 'evidence_requirements', ['effective_from'], unique=False)
    op.create_index(op.f('ix_evidence_requirements_effective_to'), 'evidence_requirements', ['effective_to'], unique=False)
    op.create_index(op.f('ix_evidence_requirements_requirement_code'), 'evidence_requirements', ['requirement_code'], unique=False)
    op.create_index(op.f('ix_evidence_requirements_status'), 'evidence_requirements', ['status'], unique=False)
    op.create_table('remediation_templates',
    sa.Column('template_code', sa.String(length=50), nullable=False),
    sa.Column('control_test_version_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('suggested_steps', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('default_owner_type', sa.Enum('COMPLIANCE_MANAGER', 'OPERATIONS_MANAGER', 'FLEET_MANAGER', 'SITE_MANAGER', 'SCHEDULER', 'EXECUTIVE', 'SUPPLIER_MANAGER', name='control_owner_type', native_enum=False), nullable=False),
    sa.Column('default_due_days', sa.Integer(), nullable=False),
    sa.Column('requires_closure_evidence', sa.Boolean(), nullable=False),
    sa.Column('requires_effectiveness_check', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'IN_REVIEW', 'APPROVED', 'ACTIVE', 'SUPERSEDED', 'RETIRED', name='lifecycle_status', native_enum=False), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('source_reference', sa.String(length=500), nullable=True),
    sa.Column('reviewed_by_id', sa.UUID(), nullable=True),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['control_test_version_id'], ['control_test_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_code', 'version', name='uq_remediation_template_version')
    )
    op.create_index(op.f('ix_remediation_templates_control_test_version_id'), 'remediation_templates', ['control_test_version_id'], unique=False)
    op.create_index(op.f('ix_remediation_templates_effective_from'), 'remediation_templates', ['effective_from'], unique=False)
    op.create_index(op.f('ix_remediation_templates_effective_to'), 'remediation_templates', ['effective_to'], unique=False)
    op.create_index(op.f('ix_remediation_templates_status'), 'remediation_templates', ['status'], unique=False)
    op.create_index(op.f('ix_remediation_templates_template_code'), 'remediation_templates', ['template_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_remediation_templates_template_code'), table_name='remediation_templates')
    op.drop_index(op.f('ix_remediation_templates_status'), table_name='remediation_templates')
    op.drop_index(op.f('ix_remediation_templates_effective_to'), table_name='remediation_templates')
    op.drop_index(op.f('ix_remediation_templates_effective_from'), table_name='remediation_templates')
    op.drop_index(op.f('ix_remediation_templates_control_test_version_id'), table_name='remediation_templates')
    op.drop_table('remediation_templates')
    op.drop_index(op.f('ix_evidence_requirements_status'), table_name='evidence_requirements')
    op.drop_index(op.f('ix_evidence_requirements_requirement_code'), table_name='evidence_requirements')
    op.drop_index(op.f('ix_evidence_requirements_effective_to'), table_name='evidence_requirements')
    op.drop_index(op.f('ix_evidence_requirements_effective_from'), table_name='evidence_requirements')
    op.drop_index(op.f('ix_evidence_requirements_control_test_version_id'), table_name='evidence_requirements')
    op.drop_table('evidence_requirements')
    op.drop_index(op.f('ix_control_risk_links_risk_id'), table_name='control_risk_links')
    op.drop_index(op.f('ix_control_risk_links_control_id'), table_name='control_risk_links')
    op.drop_table('control_risk_links')
    op.drop_index(op.f('ix_risks_status'), table_name='risks')
    op.drop_index(op.f('ix_risks_risk_code'), table_name='risks')
    op.drop_index(op.f('ix_risks_obligation_id'), table_name='risks')
    op.drop_index(op.f('ix_risks_effective_to'), table_name='risks')
    op.drop_index(op.f('ix_risks_effective_from'), table_name='risks')
    op.drop_table('risks')
    op.drop_index(op.f('ix_control_test_versions_test_type'), table_name='control_test_versions')
    op.drop_index(op.f('ix_control_test_versions_status'), table_name='control_test_versions')
    op.drop_index(op.f('ix_control_test_versions_effective_to'), table_name='control_test_versions')
    op.drop_index(op.f('ix_control_test_versions_effective_from'), table_name='control_test_versions')
    op.drop_index(op.f('ix_control_test_versions_control_test_id'), table_name='control_test_versions')
    op.drop_table('control_test_versions')
    op.drop_index(op.f('ix_applicability_rules_status'), table_name='applicability_rules')
    op.drop_index(op.f('ix_applicability_rules_rule_code'), table_name='applicability_rules')
    op.drop_index(op.f('ix_applicability_rules_obligation_id'), table_name='applicability_rules')
    op.drop_index(op.f('ix_applicability_rules_effective_to'), table_name='applicability_rules')
    op.drop_index(op.f('ix_applicability_rules_effective_from'), table_name='applicability_rules')
    op.drop_table('applicability_rules')
    op.drop_index(op.f('ix_regulation_versions_status'), table_name='regulation_versions')
    op.drop_index(op.f('ix_regulation_versions_regulation_id'), table_name='regulation_versions')
    op.drop_index(op.f('ix_regulation_versions_effective_to'), table_name='regulation_versions')
    op.drop_index(op.f('ix_regulation_versions_effective_from'), table_name='regulation_versions')
    op.drop_table('regulation_versions')
    op.drop_index(op.f('ix_obligations_status'), table_name='obligations')
    op.drop_index(op.f('ix_obligations_regulation_id'), table_name='obligations')
    op.drop_index(op.f('ix_obligations_obligation_code'), table_name='obligations')
    op.drop_index(op.f('ix_obligations_effective_to'), table_name='obligations')
    op.drop_index(op.f('ix_obligations_effective_from'), table_name='obligations')
    op.drop_table('obligations')
    op.drop_index(op.f('ix_control_versions_status'), table_name='control_versions')
    op.drop_index(op.f('ix_control_versions_effective_to'), table_name='control_versions')
    op.drop_index(op.f('ix_control_versions_effective_from'), table_name='control_versions')
    op.drop_index(op.f('ix_control_versions_control_id'), table_name='control_versions')
    op.drop_table('control_versions')
    op.drop_index(op.f('ix_control_tests_test_code'), table_name='control_tests')
    op.drop_index(op.f('ix_control_tests_control_id'), table_name='control_tests')
    op.drop_table('control_tests')
    op.drop_index(op.f('ix_regulatory_sources_source_code'), table_name='regulatory_sources')
    op.drop_table('regulatory_sources')
    op.drop_index(op.f('ix_regulations_regulation_code'), table_name='regulations')
    op.drop_table('regulations')
    op.drop_index(op.f('ix_controls_domain'), table_name='controls')
    op.drop_index(op.f('ix_controls_control_code'), table_name='controls')
    op.drop_table('controls')
    # ### end Alembic commands ###
