"""catalogue import provenance

Revision ID: be9ed4613f36
Revises: 8be45f9c97b9
Create Date: 2026-08-19 21:56:40.047550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be9ed4613f36'
down_revision: Union[str, None] = '8be45f9c97b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalogue_import_records',
    sa.Column('source_file', sa.String(length=255), nullable=False),
    sa.Column('source_version', sa.String(length=50), nullable=False),
    sa.Column('source_checksum', sa.String(length=64), nullable=False),
    sa.Column('source_entity_id', sa.String(length=255), nullable=False),
    sa.Column('target_table', sa.String(length=100), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('review_reasons', postgresql.ARRAY(sa.String(length=100)), nullable=False),
    sa.Column('source_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_file', 'source_entity_id', 'target_table', name='uq_catalogue_import_record')
    )
    op.create_index(op.f('ix_catalogue_import_records_needs_review'), 'catalogue_import_records', ['needs_review'], unique=False)
    op.create_index(op.f('ix_catalogue_import_records_source_entity_id'), 'catalogue_import_records', ['source_entity_id'], unique=False)
    op.create_index(op.f('ix_catalogue_import_records_source_file'), 'catalogue_import_records', ['source_file'], unique=False)
    op.create_index(op.f('ix_catalogue_import_records_target_id'), 'catalogue_import_records', ['target_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_catalogue_import_records_target_id'), table_name='catalogue_import_records')
    op.drop_index(op.f('ix_catalogue_import_records_source_file'), table_name='catalogue_import_records')
    op.drop_index(op.f('ix_catalogue_import_records_source_entity_id'), table_name='catalogue_import_records')
    op.drop_index(op.f('ix_catalogue_import_records_needs_review'), table_name='catalogue_import_records')
    op.drop_table('catalogue_import_records')
    # ### end Alembic commands ###
