"""tenancy model: organisations, membership, sites, fleets, suppliers, applicability

Revision ID: e2afb574f3bb
Revises: 
Create Date: 2026-08-19 07:47:02.898869

"""
from typing import Sequence, Union

from alembic import op
import uuid

import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2afb574f3bb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# --- Reference data -------------------------------------------------------
# Jurisdictions and CoR party types are platform-wide facts, identical for
# every tenant, so they are seeded by migration rather than per-organisation.

JURISDICTIONS = [
    # (code, name, hvnl_participant)
    ("NSW", "New South Wales", True),
    ("VIC", "Victoria", True),
    ("QLD", "Queensland", True),
    ("SA", "South Australia", True),
    ("TAS", "Tasmania", True),
    ("ACT", "Australian Capital Territory", True),
    # WA and NT are not HVNL participants; they operate their own heavy
    # vehicle legislation. Rule packs for them are explicitly out of scope
    # (docs/DECISIONS.md §1.7).
    ("WA", "Western Australia", False),
    ("NT", "Northern Territory", False),
]

# The parties in the Chain of Responsibility under the HVNL. An organisation
# may hold several of these at once.
COR_ROLES = [
    ("EMPLOYER", "Employer", "Employs a driver of a heavy vehicle."),
    ("PRIME_CONTRACTOR", "Prime contractor", "Engages a driver under a contract for services."),
    ("OPERATOR", "Operator", "Operates a heavy vehicle."),
    ("SCHEDULER", "Scheduler", "Schedules the transport of goods or passengers, or a driver's work and rest times."),
    ("CONSIGNOR", "Consignor", "Consigns goods for transport by a heavy vehicle."),
    ("CONSIGNEE", "Consignee", "Receives goods transported by a heavy vehicle."),
    ("PACKER", "Packer", "Packs goods for transport by a heavy vehicle."),
    ("LOADER", "Loader", "Loads goods onto a heavy vehicle."),
    ("UNLOADER", "Unloader", "Unloads goods from a heavy vehicle."),
    ("LOADING_MANAGER", "Loading manager", "Manages premises where heavy vehicles are loaded or unloaded."),
]


def _seed_reference_data() -> None:
    connection = op.get_bind()
    for code, name, hvnl in JURISDICTIONS:
        connection.execute(
            sa.text(
                "INSERT INTO jurisdictions (id, code, name, hvnl_participant, created_at, updated_at) "
                "VALUES (:id, :code, :name, :hvnl, now(), now())"
            ),
            {"id": uuid.uuid4(), "code": code, "name": name, "hvnl": hvnl},
        )
    for code, name, description in COR_ROLES:
        connection.execute(
            sa.text(
                "INSERT INTO cor_roles (id, code, name, description, created_at, updated_at) "
                "VALUES (:id, :code, :name, :description, now(), now())"
            ),
            {"id": uuid.uuid4(), "code": code, "name": name, "description": description},
        )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cor_roles',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cor_roles_code'), 'cor_roles', ['code'], unique=True)
    op.create_table('jurisdictions',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('hvnl_participant', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jurisdictions_code'), 'jurisdictions', ['code'], unique=True)
    op.create_table('organisations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('abn', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', name='organisation_status', native_enum=False), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organisations_slug'), 'organisations', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_platform_admin', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('accreditations',
    sa.Column('scheme', sa.Enum('HVA', 'NHVAS', 'WAHVA', 'OTHER', name='accreditation_scheme', native_enum=False), nullable=False),
    sa.Column('module', sa.Enum('MASS', 'MAINTENANCE', 'BASIC_FATIGUE', 'ADVANCED_FATIGUE', 'OTHER', name='accreditation_module', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('NOT_ACCREDITED', 'APPLIED', 'ACCREDITED', 'SUSPENDED', 'EXPIRED', 'WITHDRAWN', name='accreditation_status', native_enum=False), nullable=False),
    sa.Column('accreditation_number', sa.String(length=100), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accreditations_organisation_id'), 'accreditations', ['organisation_id'], unique=False)
    op.create_table('business_units',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['business_units.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organisation_id', 'code', name='uq_business_unit_code')
    )
    op.create_index(op.f('ix_business_units_organisation_id'), 'business_units', ['organisation_id'], unique=False)
    op.create_table('organisation_cor_roles',
    sa.Column('cor_role_id', sa.UUID(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cor_role_id'], ['cor_roles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organisation_id', 'cor_role_id', name='uq_organisation_cor_role')
    )
    op.create_index(op.f('ix_organisation_cor_roles_cor_role_id'), 'organisation_cor_roles', ['cor_role_id'], unique=False)
    op.create_index(op.f('ix_organisation_cor_roles_organisation_id'), 'organisation_cor_roles', ['organisation_id'], unique=False)
    op.create_table('organisation_jurisdictions',
    sa.Column('jurisdiction_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['jurisdiction_id'], ['jurisdictions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organisation_id', 'jurisdiction_id', name='uq_organisation_jurisdiction')
    )
    op.create_index(op.f('ix_organisation_jurisdictions_jurisdiction_id'), 'organisation_jurisdictions', ['jurisdiction_id'], unique=False)
    op.create_index(op.f('ix_organisation_jurisdictions_organisation_id'), 'organisation_jurisdictions', ['organisation_id'], unique=False)
    op.create_table('organisation_users',
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('PLATFORM_ADMIN', 'ORG_ADMIN', 'COMPLIANCE_MANAGER', 'OPERATIONS_MANAGER', 'EXECUTIVE', 'AUDITOR', 'READ_ONLY', name='organisation_role', native_enum=False), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organisation_id', 'user_id', name='uq_organisation_user')
    )
    op.create_index(op.f('ix_organisation_users_organisation_id'), 'organisation_users', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_organisation_users_user_id'), 'organisation_users', ['user_id'], unique=False)
    op.create_table('suppliers',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('abn', sa.String(length=20), nullable=True),
    sa.Column('supplier_type', sa.Enum('CARRIER', 'SUBCONTRACTOR', 'OWNER_DRIVER', 'LABOUR_HIRE', 'MAINTENANCE_PROVIDER', 'OTHER', name='supplier_type', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organisation_id', 'code', name='uq_supplier_code')
    )
    op.create_index(op.f('ix_suppliers_organisation_id'), 'suppliers', ['organisation_id'], unique=False)
    op.create_table('sites',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('site_type', sa.Enum('DEPOT', 'DISTRIBUTION_CENTRE', 'LOADING_FACILITY', 'WORKSHOP', 'CUSTOMER_SITE', 'OTHER', name='site_type', native_enum=False), nullable=False),
    sa.Column('jurisdiction_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('address_line', sa.String(length=255), nullable=True),
    sa.Column('suburb', sa.String(length=120), nullable=True),
    sa.Column('postcode', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_unit_id'], ['business_units.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['jurisdiction_id'], ['jurisdictions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organisation_id', 'code', name='uq_site_code')
    )
    op.create_index(op.f('ix_sites_business_unit_id'), 'sites', ['business_unit_id'], unique=False)
    op.create_index(op.f('ix_sites_jurisdiction_id'), 'sites', ['jurisdiction_id'], unique=False)
    op.create_index(op.f('ix_sites_organisation_id'), 'sites', ['organisation_id'], unique=False)
    op.create_table('fleets',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('home_site_id', sa.UUID(), nullable=True),
    sa.Column('vehicle_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_unit_id'], ['business_units.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['home_site_id'], ['sites.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organisation_id', 'code', name='uq_fleet_code')
    )
    op.create_index(op.f('ix_fleets_business_unit_id'), 'fleets', ['business_unit_id'], unique=False)
    op.create_index(op.f('ix_fleets_home_site_id'), 'fleets', ['home_site_id'], unique=False)
    op.create_index(op.f('ix_fleets_organisation_id'), 'fleets', ['organisation_id'], unique=False)
    # ### end Alembic commands ###

    _seed_reference_data()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fleets_organisation_id'), table_name='fleets')
    op.drop_index(op.f('ix_fleets_home_site_id'), table_name='fleets')
    op.drop_index(op.f('ix_fleets_business_unit_id'), table_name='fleets')
    op.drop_table('fleets')
    op.drop_index(op.f('ix_sites_organisation_id'), table_name='sites')
    op.drop_index(op.f('ix_sites_jurisdiction_id'), table_name='sites')
    op.drop_index(op.f('ix_sites_business_unit_id'), table_name='sites')
    op.drop_table('sites')
    op.drop_index(op.f('ix_suppliers_organisation_id'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_organisation_users_user_id'), table_name='organisation_users')
    op.drop_index(op.f('ix_organisation_users_organisation_id'), table_name='organisation_users')
    op.drop_table('organisation_users')
    op.drop_index(op.f('ix_organisation_jurisdictions_organisation_id'), table_name='organisation_jurisdictions')
    op.drop_index(op.f('ix_organisation_jurisdictions_jurisdiction_id'), table_name='organisation_jurisdictions')
    op.drop_table('organisation_jurisdictions')
    op.drop_index(op.f('ix_organisation_cor_roles_organisation_id'), table_name='organisation_cor_roles')
    op.drop_index(op.f('ix_organisation_cor_roles_cor_role_id'), table_name='organisation_cor_roles')
    op.drop_table('organisation_cor_roles')
    op.drop_index(op.f('ix_business_units_organisation_id'), table_name='business_units')
    op.drop_table('business_units')
    op.drop_index(op.f('ix_accreditations_organisation_id'), table_name='accreditations')
    op.drop_table('accreditations')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_organisations_slug'), table_name='organisations')
    op.drop_table('organisations')
    op.drop_index(op.f('ix_jurisdictions_code'), table_name='jurisdictions')
    op.drop_table('jurisdictions')
    op.drop_index(op.f('ix_cor_roles_code'), table_name='cor_roles')
    op.drop_table('cor_roles')
    # ### end Alembic commands ###
